// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.13 public/models/reactMesh.glb 
// */

// import React, { useRef, useEffect } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'

// export function ReactMesh(props) {
//   const group = useRef()
//   const { nodes, materials, animations } = useGLTF('/models/reactMesh.glb')
//   const { ref, actions } = useAnimations(animations, group);
//   useEffect(() => {
//     Object.keys(actions).forEach(action => {
//         // actions[action].setLoop(LoopPingPong, Infinity)
//         console.log(actions[action])
//         actions[action]?.play();
//     })
//   })
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Scene">
//         <group name="a-axis" position={[1.522, 0.57, -0.05]}>
//           <mesh name="a" geometry={nodes.a.geometry} material={materials.small} position={[-0.128, 0, 0.093]} rotation={[0, -0.942, 0]} scale={0.79} />
//         </group>
//         <group name="b-axis" position={[1.364, 0.528, -0.167]} rotation={[Math.PI / 4, 0.377, 0]}>
//           <mesh name="b" geometry={nodes.b.geometry} material={materials.small} scale={0.79} />
//         </group>
//         <group name="c-axis" position={[1.411, 0.656, -0.122]} rotation={[2.356, 0, 0]}>
//           <mesh name="c" geometry={nodes.c.geometry} material={materials.small} scale={0.79} />
//         </group>
//         <mesh name="central" geometry={nodes.central.geometry} material={materials.large_BB} position={[1.512, 0.57, -0.208]} scale={0.35} />
//         <mesh name="a-path" geometry={nodes['a-path'].geometry} material={nodes['a-path'].material} position={[1.512, 0.57, -0.208]} scale={0.79} />
//         <mesh name="b-path" geometry={nodes['b-path'].geometry} material={materials.Material} position={[1.512, 0.57, -0.208]} rotation={[Math.PI / 4, 0, 0]} scale={0.79} />
//         <mesh name="c-path" geometry={nodes['c-path'].geometry} material={nodes['c-path'].material} position={[1.512, 0.57, -0.208]} rotation={[2.356, 0, 0]} scale={0.79} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/reactMesh.glb')
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/assets/renders/react_decent.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { LoopRepeat } from 'three'

export const ReactMesh = (props) =>  {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/reactMesh.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    names.forEach(name => {
        actions[name].play()
        actions[name].setLoop(LoopRepeat, Infinity);
        actions[name].time=0;
    },[])
    
  })
  return (
    <group ref={group} {...props} dispose={null} scale={4} position={[-6,0.9,3]} rotation={[-Math.PI/2, 0 ,0]}>
      <group name="Scene">
        <group name="a-axis" position={[1.522, 0.57, -0.05]}>
          <mesh name="a" geometry={nodes.a.geometry} material={materials.small} position={[-0.128, 0, 0.093]} rotation={[0, -0.942, 0]} scale={0.079} />
        </group>
        <group name="b-axis" position={[1.364, 0.528, -0.167]} rotation={[Math.PI / 4, 0.377, 0]}>
          <mesh name="b" geometry={nodes.b.geometry} material={materials.small} scale={0.079} />
        </group>
        <group name="c-axis" position={[1.411, 0.656, -0.122]} rotation={[2.356, 0, 0]}>
          <mesh name="c" geometry={nodes.c.geometry} material={materials.small} scale={0.079} />
        </group>
        <mesh name="central" geometry={nodes.central.geometry} material={materials.large_BB} position={[1.512, 0.57, -0.208]} scale={0.035} />
        <mesh name="a-path" geometry={nodes['a-path'].geometry} material={nodes['a-path'].material} position={[1.512, 0.57, -0.208]} scale={0.079} />
        <mesh name="b-path" geometry={nodes['b-path'].geometry} material={materials.Material} position={[1.512, 0.57, -0.208]} rotation={[Math.PI / 4, 0, 0]} scale={0.079} />
        <mesh name="c-path" geometry={nodes['c-path'].geometry} material={nodes['c-path'].material} position={[1.512, 0.57, -0.208]} rotation={[2.356, 0, 0]} scale={0.079} />
      </group>
    </group>
  )
}
// export default ReactMesh;
useGLTF.preload('/models/reactMesh.glb')
